### ISSUE TITLE
Asin vs ISBN-10 ‏product identification

### ISSUE THREAD

**Issue by celsofranssa** [hyp1231/AmazonReviews2023#14]
Some products on Amazon (https://www.amazon.com/Best-California-Maria-Cianci/dp/000255478X) don't have `asin` number. Instead, they have ISBN-10 ‏: ‎ 000255478X. 

How could I find the product title using this ISBN-10 ‏: ‎ 000255478X?

**Comment by hyp1231** [comment]
Hi, I've checked several products under the category "Books". I guess Amazon directly uses the ISBN-10 number of one book as its ASIN number. As a result, it should be fine to directly access the products using the `parent_asin` attribute.

If you can not find one specific item using their `parent_asin`, that could be possible due to:
1. Not enough reviews associated with this item. We collect the dataset in a user-centric manner, which means that we first collect a pool of users, and then collect all the reviews of each user, then collect the metadata of the associated products. If there is no review associated with one product, then it could be possible that the product 
2. Time lag: Collecting the dataset takes time, so some recent reviews may be missing (even before the cut-off time).
3. Technical issues: The collection may encounter network issues, parsing errors, or others.

**Comment by celsofranssa** [comment]
For instance, I am trying to find the '0781438772' product. Then, searching for it on the Amazon e-commerce website, we find the [book](https://www.amazon.com/Basic-Bible-Interpretation-Roy-Zuck/dp/0781438772/ref=sr_1_1?crid=O0YVKIPKKVOY&dib=eyJ2IjoiMSJ9.ita2lrF770aCH4pIVG8OgA.9aUABSBvMBB4NV5dUbxlqK8XL2YKIDxRWoJZU12Bk6s&dib_tag=se&keywords=0781438772&qid=1724458557&s=books&sprefix=0781438772%2Cstripbooks-intl-ship%2C370&sr=1-1): "Basic Bible Interpretation" which has 514 ratings.

**Comment by celsofranssa** [comment]
> 0781438772

Recently, I discovered that this book is associated with "0896938190" (in the Books category) instead of what appears on the Amazon website (0781438772).

**Comment by celsofranssa** [comment]
> > 0781438772
> 
> Recently, I discovered that this book is associated with "0896938190" (in the Books category) instead of what appears on the Amazon website (0781438772).

It is the same fo the book  [Miss Hobbema Pageant](https://www.amazon.com.br/Miss-Hobbema-Pageant-W-Kinsella/dp/000647960X/ref=sr_1_1?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2FPQ1LGZ3W0FA&dib=eyJ2IjoiMSJ9.bKYpAyVQ7kW4nb-GxzQYrA.s9xEn7GK_VZNPVA2ljJ55rplIwwCKvNn5ue-GliDkAI&dib_tag=se&keywords=000647960x&qid=1724470887&sprefix=000647960x%2Caps%2C233&sr=8-1), which appears with asin equal to `0002234947` while in Amazon, it appears associated with `000647960X`.

**Comment by hyp1231** [comment]
For the Bible example, it appears that the two ISBN-10s refer to different editions of a book with the same title, content, and author. So, the behavior seems expected, as the platform treats them as two distinct books. Please let me know if I’ve misunderstood anything.

## 0781438772

Amazon:
<img width="1373" alt="image" src="https://github.com/user-attachments/assets/63d1bf32-5584-4239-b937-432970357be8">

Search ISBN-10 on Abebooks:
<img width="1268" alt="image" src="https://github.com/user-attachments/assets/094f810d-d3c9-4c84-8bf3-f908124a4fc0">

## 0896938190

Amazon:
<img width="1373" alt="image" src="https://github.com/user-attachments/assets/e927461a-4f18-4d0e-8a96-be4e01986b6d">

Search ISBN-10 on Abebooks:
<img width="1310" alt="image" src="https://github.com/user-attachments/assets/0a2826c3-2a5e-4492-bbbb-7832c2a3e87b">
